title: CODIGUIN
email: gabrielbelo.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Esse é um blog acadêmico, onde serão postados conteúdos diversos relacionados aos meus estudos no CIn - UFPE, 
  enquanto graduando em IA.
url: "gabrielbelo2007.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gabrielbelo2007
lang: pt-BR

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM 
plugins:
  - jekyll-feed
